<?php
/**
 * @file
 * Hook implementations for client_error_trace.
 */

/**
 * Implements hook_menu().
 */
function client_error_trace_menu() {
  $items = array();

  $items['admin/reports/client-error-trace'] = array(
    'title' => 'Client error trace',
    'description' => 'Run tests to help find the root cause of 4XX errors.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('client_error_trace_form'),
    'access arguments' => array('administer site'),
    'file' => 'client_error_trace.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function client_error_trace_theme($existing, $type, $theme, $path) {
  return array(
    'client_error_trace_report' => array(
      'variables' => array('url' => NULL, 'results' => NULL),
      'path' => drupal_get_path('module', 'client_error_trace') . '/template',
      'template' => 'client_error_trace_report',
    ),
    'client_error_trace_item' => array(
      'variables' => array(
        'result' => NULL,
        'description' => NULL,
        'message' => NULL,
        'suggestions' => NULL,
      ),
      'path' => drupal_get_path('module', 'client_error_trace') . '/template',
      'template' => 'client_error_trace_item',
    ),
  );
}
