<?php

/**
 * Implements hook_menu().
 */
function client_error_trace_menu() {
  $items = array();

  $items['admin/reports/client-error-trace'] = array(
    'title' => 'Client error trace',
    'description' => 'Run tests to help find the root cause of 4XX errors.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('client_error_trace_form'),
    'access arguments' => array('administer site'),
    'file' => 'client_error_trace.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
